#!/usr/bin/env python3
"""Generate the opcode and update-field tables in agent/ from TrinityCore (#290).

    scripts/gen_protocol_tables.py            rewrite the tables from the vendored excerpts
    scripts/gen_protocol_tables.py --check    exit 1 if a committed table differs (CI)
    scripts/gen_protocol_tables.py --source <TrinityCore checkout> --commit <sha> [--add NAME ...]
                                              refresh the excerpts from the real headers, then rewrite

The excerpts in scripts/trinitycore-excerpt/ hold the header lines the agent uses,
verbatim, plus the commit they were read at. They are the selection: `--add` is how a new
opcode or field gets in. The tables are the text between BEGIN and END in each target.
"""
import argparse
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
EXCERPTS = ROOT / "scripts/trinitycore-excerpt"
BEGIN = "# --- BEGIN GENERATED by scripts/gen_protocol_tables.py: do not edit by hand ---"
END = "# --- END GENERATED ---"

ENUM = re.compile(r"^\s*enum\s+(\w+)")
ENTRY = re.compile(r"^\s*(\w+)\s*=\s*([^,/]+?)\s*,?\s*(?://\s*(.*?))?\s*$")
COMMIT = re.compile(r"^// commit ([0-9a-f]{40})$", re.M)

# Opcodes.h name -> the name agent/ already uses for it (same value).
OPCODE_NAMES = {
    "CMSG_ATTACK_SWING": "CMSG_ATTACKSWING",
    "CMSG_ATTACK_STOP": "CMSG_ATTACKSTOP",
    "SMSG_QUEST_GIVER_QUEST_DETAILS": "SMSG_QUESTGIVER_QUEST_DETAILS",
    "SMSG_QUEST_GIVER_OFFER_REWARD_MESSAGE": "SMSG_QUESTGIVER_OFFER_REWARD",
}
# Repo name -> trailing note. Payload layouts belong in docs/PROTOCOL-NOTES.md; these are
# the one-liners the hand-written table carried.
OPCODE_NOTES = {
    "SMSG_GROUP_DECLINE": "GroupHandler.cpp: cstring name of the invitee who declined",
    "SMSG_GROUP_UNINVITE": "empty; Group::RemoveMember sends it on a kick",
    "SMSG_GROUP_DESTROYED": "empty; Group::Disband",
    "SMSG_GROUP_LIST": "see agent/group.py",
    "CMSG_MESSAGECHAT": "chat say/yell/whisper/emote",
    "CMSG_SET_SELECTION": "target a GUID",
    "CMSG_REPOP_REQUEST": "payload: uint8 CheckInstance (always 0 from a real client)",
    "CMSG_RECLAIM_CORPSE": "payload: uint64 CorpseGUID (raw, not packed — ObjectGuid::operator>>)",
    "MSG_CORPSE_QUERY": "empty client->server request",
    "CMSG_SPIRIT_HEALER_ACTIVATE": "payload: uint64 guid (raw)",
    "SMSG_CORPSE_RECLAIM_DELAY": "payload: uint32 Remaining (ms)",
    "SMSG_DEATH_RELEASE_LOC": "payload: int32 MapID, float x, y, z",
}


def parse(text):
    """[(enum, name, expression, comment)] for every `NAME = value` line, in file order."""
    out, enum = [], ""
    for line in text.splitlines():
        if m := ENUM.match(line):
            enum = m.group(1)
        elif m := ENTRY.match(line):
            out.append((enum, m.group(1), m.group(2), m.group(3) or ""))
    return out


def commit_of(text):
    m = COMMIT.search(text)
    if not m:
        sys.exit("excerpt has no `// commit <sha>` line")
    return m.group(1)


PATHS = {  # header -> path in TrinityCore
    "Opcodes.h": "src/server/game/Server/Protocol/Opcodes.h",
    "UpdateFields.h": "src/server/game/Entities/Object/Updates/UpdateFields.h",
}


def _source_line(header, commit):
    return f"# TrinityCore 3.3.5 {PATHS[header]} @ {commit}\n"


def render_update_fields(entries, commit):
    """Expressions verbatim, so `OBJECT_END + n` / `UNIT_END + n` read like the header."""
    out, enum = [_source_line("UpdateFields.h", commit)], None
    for e, name, expr, comment in entries:
        if e != enum:
            out.append(f"\n# {e}\n")
            enum = e
        out.append(f"{name} = {expr}" + (f"  # {comment}" if comment else "") + "\n")
    return "".join(out)


def render_opcodes(entries, commit):
    out = [_source_line("Opcodes.h", commit)]
    for _, header_name, expr, _ in sorted(entries, key=lambda e: int(e[2], 16)):
        name = OPCODE_NAMES.get(header_name, header_name)
        note = f"Opcodes.h name: {header_name}" if name != header_name else OPCODE_NOTES.get(name, "")
        out.append(f"{name:<32} = 0x{int(expr, 16):03X}" + (f"  # {note}" if note else "") + "\n")
    return "".join(out)


TABLES = {  # header -> (target, renderer)
    "Opcodes.h": ("agent/opcodes.py", render_opcodes),
    "UpdateFields.h": ("agent/update_fields.py", render_update_fields),
}


def excerpt(header_text, names, header, commit):
    """The header's lines for `names` (verbatim, under their `enum` line) plus the commit."""
    lines, enum, seen = [], "", set()
    for line in header_text.splitlines():
        if ENUM.match(line):
            enum = line.strip()
        elif (m := ENTRY.match(line)) and m.group(1) in names:
            if enum:
                lines.append(enum)
                enum = ""
            lines.append(line.rstrip())
            seen.add(m.group(1))
    if missing := sorted(set(names) - seen):
        sys.exit(f"not in {header}: {', '.join(missing)}")
    head = (f"// Excerpt of TrinityCore (GPL-2.0) {PATHS[header]}\n// commit {commit}\n"
            "// Written by scripts/gen_protocol_tables.py --source: do not edit by hand.\n")
    return head + "\n".join(lines) + "\n"


def generated(header):
    text = (EXCERPTS / header).read_text()
    return TABLES[header][1](parse(text), commit_of(text))


def splice(old, block):
    head, sep, rest = old.partition(BEGIN + "\n")
    _, sep2, tail = rest.partition(END)
    if not sep or not sep2:
        sys.exit("BEGIN/END GENERATED markers not found")
    return head + sep + block + END + tail


def sync(path, block, check):
    """Write the block into `path`; with check=True only report. Returns 1 on drift."""
    old = path.read_text()
    new = splice(old, block)
    if new == old:
        return 0
    if check:
        print(f"{path}: differs from the generator's output; run scripts/gen_protocol_tables.py "
              "(never edit the generated block by hand)", file=sys.stderr)
        return 1
    path.write_text(new)
    print(f"wrote {path}")
    return 0


def refresh(source, commit, add):
    """Rewrite the excerpts from a TrinityCore checkout (or a directory holding the two headers)."""
    if (source / ".git").exists():
        head = subprocess.run(["git", "-C", str(source), "rev-parse", "HEAD"],
                              capture_output=True, text=True, check=True).stdout.strip()
        if head != commit:
            sys.exit(f"--commit {commit} but {source} is at {head}")
    add, writes = set(add), {}
    for header, tc_path in PATHS.items():
        path = source / tc_path if (source / tc_path).exists() else source / header
        text = path.read_text()
        old = EXCERPTS / header
        names = {e[1] for e in parse(old.read_text())} if old.exists() else set()
        mine = add & {e[1] for e in parse(text)}
        add -= mine
        writes[old] = excerpt(text, names | mine, header, commit)
    if add:
        sys.exit(f"in neither header: {', '.join(sorted(add))}")
    EXCERPTS.mkdir(exist_ok=True)
    for path, text in writes.items():
        path.write_text(text)


def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--check", action="store_true", help="report drift, write nothing")
    p.add_argument("--source", type=pathlib.Path, help="TrinityCore checkout (branch 3.3.5)")
    p.add_argument("--commit", help="the 40-hex commit --source is at")
    p.add_argument("--add", nargs="+", default=[], metavar="NAME", help="header names to add (with --source)")
    args = p.parse_args(argv)
    if args.source:
        if args.check or not re.fullmatch(r"[0-9a-f]{40}", args.commit or ""):
            p.error("--source needs --commit <40-hex sha> and cannot be combined with --check")
        refresh(args.source, args.commit, args.add)
    elif args.add or args.commit:
        p.error("--add and --commit need --source")
    return max(sync(ROOT / target, generated(header), args.check) for header, (target, _) in TABLES.items())


if __name__ == "__main__":
    sys.exit(main())
