"""Names of the registered actions: the one place an action name is spelled outside its own class.
Candidates (and anything else that refers to an action) use these constants, so a typo is an
AttributeError at import instead of a silent miss at runtime. A test pins this module against
agent.actions.REGISTRY in both directions. Pure values; imports nothing from agent/."""

SET_TARGET = "set_target"
FACE = "face"
MOVE_TO = "move_to"
MOVE_TOWARDS = "move_towards"
STOP_MOVEMENT = "stop_movement"
AUTO_ATTACK = "auto_attack"
STOP_ATTACK = "stop_attack"
IDLE = "idle"
CAST_SPELL = "cast_spell"
INTERACT = "interact"
GOSSIP_SELECT = "gossip_select"
BUY_ITEM = "buy_item"
SELL_ITEM = "sell_item"
TRAIN_SPELL = "train_spell"
INVITE_TO_GROUP = "invite_to_group"
ACCEPT_GROUP = "accept_group"
DECLINE_GROUP = "decline_group"
LEAVE_GROUP = "leave_group"
PROMOTE_LEADER = "promote_leader"
CLOSE_WINDOW = "close_window"
LOOT = "loot"
USE_ITEM = "use_item"
DESTROY_ITEM = "destroy_item"
COMPARE_ITEMS = "compare_items"
EQUIP_ITEM = "equip_item"
ACCEPT_QUEST = "accept_quest"
COMPLETE_QUEST = "complete_quest"
TURN_IN_QUEST = "turn_in_quest"
ABANDON_QUEST = "abandon_quest"
OPEN_TRADE = "open_trade"
ACCEPT_TRADE_REQUEST = "accept_trade_request"
OFFER_ITEM = "offer_item"
OFFER_GOLD = "offer_gold"
ACCEPT_TRADE = "accept_trade"
CANCEL_TRADE = "cancel_trade"
OPEN_MAILBOX = "open_mailbox"
SEND_MAIL = "send_mail"
TAKE_MAIL = "take_mail"
DELETE_MAIL = "delete_mail"
RELEASE_SPIRIT = "release_spirit"
RECLAIM_CORPSE = "reclaim_corpse"
FOLLOW = "follow"
ASSIST = "assist"
STOP_FOLLOWING = "stop_following"
REST = "rest"
