"""Every SMSG_/CMSG_/MSG_ opcode the agent uses, in one place (#247).

Values are checked against TrinityCore `3.3.5` branch,
src/server/game/Server/Protocol/Opcodes.h. Domain modules import from here and
keep only their payload layouts; tests/test_opcodes.py fails on duplicate names
or values and on router registrations missing from this file.

Where the repo's name differs from Opcodes.h the header name is in a comment;
the value is the same. Plain ints (not an Enum) so router dict keys and
struct packing stay exactly as before.
"""

CMSG_CHAR_CREATE                 = 0x036
CMSG_CHAR_ENUM                   = 0x037
SMSG_CHAR_CREATE                 = 0x03A
SMSG_CHAR_ENUM                   = 0x03B
CMSG_PLAYER_LOGIN                = 0x03D
CMSG_LOGOUT_REQUEST              = 0x04B
SMSG_LOGOUT_COMPLETE             = 0x04D
CMSG_NAME_QUERY                  = 0x050
SMSG_NAME_QUERY_RESPONSE         = 0x051
CMSG_ITEM_QUERY_SINGLE           = 0x056
SMSG_ITEM_QUERY_SINGLE_RESPONSE  = 0x058
CMSG_QUEST_QUERY                 = 0x05C
SMSG_QUEST_QUERY_RESPONSE        = 0x05D
CMSG_GAMEOBJECT_QUERY            = 0x05E
SMSG_GAMEOBJECT_QUERY_RESPONSE   = 0x05F
CMSG_CREATURE_QUERY              = 0x060
SMSG_CREATURE_QUERY_RESPONSE     = 0x061
CMSG_GROUP_INVITE                = 0x06E
SMSG_GROUP_INVITE                = 0x06F
CMSG_GROUP_ACCEPT                = 0x072
CMSG_GROUP_DECLINE              = 0x073
SMSG_GROUP_DECLINE              = 0x074  # GroupHandler.cpp: cstring name of the invitee who declined
SMSG_GROUP_UNINVITE             = 0x077  # empty; Group::RemoveMember sends it on a kick
CMSG_GROUP_SET_LEADER           = 0x078
CMSG_GROUP_DISBAND               = 0x07B
SMSG_GROUP_DESTROYED            = 0x07C  # empty; Group::Disband
SMSG_GROUP_LIST                 = 0x07D  # see agent/group.py
SMSG_PARTY_COMMAND_RESULT        = 0x07F
CMSG_MESSAGECHAT                 = 0x095  # chat say/yell/whisper/emote
SMSG_MESSAGECHAT                 = 0x096
CMSG_JOIN_CHANNEL                = 0x097
CMSG_LEAVE_CHANNEL               = 0x098
SMSG_CHANNEL_NOTIFY              = 0x099
CMSG_AUTOEQUIP_ITEM              = 0x10A
SMSG_UPDATE_OBJECT               = 0x0A9
SMSG_DESTROY_OBJECT              = 0x0AA
CMSG_USE_ITEM                    = 0x0AB
CMSG_GAMEOBJ_USE                 = 0x0B1
MSG_MOVE_START_FORWARD           = 0x0B5
MSG_MOVE_START_BACKWARD          = 0x0B6
MSG_MOVE_STOP                    = 0x0B7
MSG_MOVE_START_STRAFE_LEFT       = 0x0B8
MSG_MOVE_START_STRAFE_RIGHT      = 0x0B9
MSG_MOVE_STOP_STRAFE             = 0x0BA
MSG_MOVE_JUMP                    = 0x0BB
MSG_MOVE_START_TURN_LEFT         = 0x0BC
MSG_MOVE_START_TURN_RIGHT        = 0x0BD
MSG_MOVE_STOP_TURN               = 0x0BE
MSG_MOVE_SET_RUN_MODE            = 0x0C2
MSG_MOVE_SET_WALK_MODE           = 0x0C3
MSG_MOVE_FALL_LAND               = 0x0C9
MSG_MOVE_START_SWIM              = 0x0CA
MSG_MOVE_STOP_SWIM               = 0x0CB
MSG_MOVE_SET_FACING              = 0x0DA
SMSG_MONSTER_MOVE                = 0x0DD
MSG_MOVE_HEARTBEAT               = 0x0EE
SMSG_TUTORIAL_FLAGS              = 0x0FD
CMSG_STANDSTATECHANGE            = 0x101
CMSG_TEXT_EMOTE                  = 0x104
CMSG_AUTOSTORE_LOOT_ITEM         = 0x108
CMSG_DESTROYITEM                 = 0x111
SMSG_INVENTORY_CHANGE_FAILURE    = 0x112
CMSG_INITIATE_TRADE              = 0x116
CMSG_BEGIN_TRADE                 = 0x117
CMSG_BUSY_TRADE                  = 0x118
CMSG_IGNORE_TRADE                = 0x119
CMSG_ACCEPT_TRADE                = 0x11A
CMSG_UNACCEPT_TRADE              = 0x11B
CMSG_CANCEL_TRADE                = 0x11C
CMSG_SET_TRADE_ITEM              = 0x11D
CMSG_CLEAR_TRADE_ITEM            = 0x11E
CMSG_SET_TRADE_GOLD              = 0x11F
SMSG_TRADE_STATUS                = 0x120
SMSG_TRADE_STATUS_EXTENDED       = 0x121
SMSG_INITIAL_SPELLS              = 0x12A
SMSG_LEARNED_SPELL               = 0x12B
CMSG_CAST_SPELL                  = 0x12E
SMSG_CAST_FAILED                 = 0x130
SMSG_SPELL_START                 = 0x131
SMSG_SPELL_GO                    = 0x132
CMSG_SET_SELECTION               = 0x13D  # target a GUID
CMSG_ATTACKSWING                 = 0x141  # Opcodes.h name: CMSG_ATTACK_SWING
CMSG_ATTACKSTOP                  = 0x142  # Opcodes.h name: CMSG_ATTACK_STOP
SMSG_ATTACK_START                = 0x143
SMSG_ATTACK_STOP                 = 0x144
SMSG_ATTACKERSTATEUPDATE         = 0x14A
CMSG_REPOP_REQUEST               = 0x15A  # payload: uint8 CheckInstance (always 0 from a real client)
CMSG_LOOT                        = 0x15D
CMSG_LOOT_MONEY                  = 0x15E
CMSG_LOOT_RELEASE                = 0x15F
SMSG_LOOT_RESPONSE               = 0x160
SMSG_LOOT_RELEASE_RESPONSE       = 0x161
SMSG_LOOT_REMOVED                = 0x162
SMSG_LOOT_MONEY_NOTIFY           = 0x163
SMSG_LOOT_CLEAR_MONEY            = 0x165
SMSG_ITEM_PUSH_RESULT            = 0x166
CMSG_GOSSIP_HELLO                = 0x17B
CMSG_GOSSIP_SELECT_OPTION        = 0x17C
SMSG_GOSSIP_MESSAGE              = 0x17D
SMSG_GOSSIP_COMPLETE             = 0x17E
CMSG_NPC_TEXT_QUERY              = 0x17F
SMSG_NPC_TEXT_UPDATE             = 0x180
CMSG_QUESTGIVER_STATUS_QUERY     = 0x182
SMSG_QUESTGIVER_STATUS           = 0x183
CMSG_QUESTGIVER_HELLO            = 0x184
SMSG_QUESTGIVER_QUEST_LIST       = 0x185
CMSG_QUESTGIVER_QUERY_QUEST      = 0x186
SMSG_QUESTGIVER_QUEST_DETAILS    = 0x188  # Opcodes.h name: SMSG_QUEST_GIVER_QUEST_DETAILS
CMSG_QUESTGIVER_ACCEPT_QUEST     = 0x189
CMSG_QUESTGIVER_COMPLETE_QUEST   = 0x18A
SMSG_QUESTGIVER_REQUEST_ITEMS    = 0x18B
CMSG_QUESTGIVER_REQUEST_REWARD   = 0x18C
SMSG_QUESTGIVER_OFFER_REWARD     = 0x18D  # Opcodes.h name: SMSG_QUEST_GIVER_OFFER_REWARD_MESSAGE
CMSG_QUESTGIVER_CHOOSE_REWARD    = 0x18E
CMSG_QUESTGIVER_CANCEL           = 0x190
SMSG_QUESTGIVER_QUEST_COMPLETE   = 0x191
SMSG_QUESTGIVER_QUEST_FAILED     = 0x192
CMSG_QUESTLOG_REMOVE_QUEST       = 0x194
SMSG_QUESTUPDATE_COMPLETE        = 0x198
SMSG_QUESTUPDATE_ADD_KILL        = 0x199
SMSG_QUESTUPDATE_ADD_ITEM        = 0x19A
CMSG_LIST_INVENTORY              = 0x19E
SMSG_LIST_INVENTORY              = 0x19F
CMSG_SELL_ITEM                   = 0x1A0
SMSG_SELL_ITEM                   = 0x1A1
CMSG_BUY_ITEM                    = 0x1A2
CMSG_BUY_ITEM_IN_SLOT            = 0x1A3
SMSG_BUY_ITEM                    = 0x1A4
SMSG_BUY_FAILED                  = 0x1A5
CMSG_TRAINER_LIST                = 0x1B0
SMSG_TRAINER_LIST                = 0x1B1
CMSG_TRAINER_BUY_SPELL           = 0x1B2
SMSG_TRAINER_BUY_SUCCEEDED       = 0x1B3
SMSG_TRAINER_BUY_FAILED          = 0x1B4
SMSG_LOG_XPGAIN                  = 0x1D0
CMSG_RECLAIM_CORPSE              = 0x1D2  # payload: uint64 CorpseGUID (raw, not packed — ObjectGuid::operator>>)
SMSG_LEVELUP_INFO                = 0x1D4
CMSG_PING                        = 0x1DC
SMSG_PONG                        = 0x1DD
SMSG_AUTH_CHALLENGE              = 0x1EC
CMSG_AUTH_SESSION                = 0x1ED
SMSG_AUTH_RESPONSE               = 0x1EE
SMSG_PARTYKILLLOG                = 0x1F5
SMSG_COMPRESSED_UPDATE_OBJECT    = 0x1F6
SMSG_REMOVED_SPELL               = 0x203
MSG_CORPSE_QUERY                 = 0x216  # empty client->server request
CMSG_SPIRIT_HEALER_ACTIVATE      = 0x21C  # payload: uint64 guid (raw)
SMSG_LOGIN_VERIFY_WORLD          = 0x236
CMSG_SEND_MAIL                   = 0x238
SMSG_SEND_MAIL_RESULT            = 0x239
CMSG_GET_MAIL_LIST               = 0x23A
SMSG_MAIL_LIST_RESULT            = 0x23B
CMSG_MAIL_TAKE_MONEY             = 0x245
CMSG_MAIL_TAKE_ITEM              = 0x246
CMSG_MAIL_MARK_AS_READ           = 0x247
CMSG_MAIL_RETURN_TO_SENDER       = 0x248
CMSG_MAIL_DELETE                 = 0x249
SMSG_SPELLNONMELEEDAMAGELOG      = 0x250
SMSG_CORPSE_RECLAIM_DELAY        = 0x269  # payload: uint32 Remaining (ms)
CMSG_SET_ACTIVE_MOVER            = 0x26A
SMSG_RECEIVED_MAIL               = 0x285
SMSG_STANDSTATE_UPDATE           = 0x29D
SMSG_CHAT_PLAYER_NOT_FOUND       = 0x2A9
SMSG_ADDON_INFO                  = 0x2EF
SMSG_DEATH_RELEASE_LOC           = 0x378  # payload: int32 MapID, float x, y, z
SMSG_TIME_SYNC_REQ               = 0x390
CMSG_TIME_SYNC_RESP              = 0x391
SMSG_GM_MESSAGECHAT              = 0x3B3
CMSG_KEEP_ALIVE                  = 0x407
