#!/usr/bin/env python3
"""VALUES_UPDATE field indices and decoding (WoW 3.3.5a, build 12340).

The field indices between the GENERATED markers come from TrinityCore branch
`3.3.5`, src/server/game/Entities/Object/Updates/UpdateFields.h (the commit is
recorded in the block), whose own header comment reads "Auto generated for
version 3, 3, 5, 12340" — the exact build this repo's client speaks. They are
written by scripts/gen_protocol_tables.py (#290) and CI fails if the block is
edited by hand; to add a field run
`scripts/gen_protocol_tables.py --source <TrinityCore checkout> --commit <sha> --add <NAME>`
(docs/PROTOCOL-NOTES.md, "Generated tables"). The removed handoff doc's field
table (ENTRY=0x02, HEALTH=0x21, ...) does NOT match this source; don't use it.

Field values in EObjectFields (OBJECT_FIELD_GUID..OBJECT_FIELD_PADDING) are
absolute indices. Every other enum's members are written as `OBJECT_END +
n` / `UNIT_END + n` in the header, and the generator copies that expression
verbatim. PLAYER_* fields sit in EUnitFields after UNIT_END, as in the header.
"""

import struct

from . import update_object as uo

# --- BEGIN GENERATED by scripts/gen_protocol_tables.py: do not edit by hand ---
# TrinityCore 3.3.5 src/server/game/Entities/Object/Updates/UpdateFields.h @ 41d89b32c01577508005bad98992d76b0b1abc43

# EObjectFields
OBJECT_FIELD_GUID = 0x0000  # Size: 2, Type: LONG, Flags: PUBLIC
OBJECT_FIELD_TYPE = 0x0002  # Size: 1, Type: INT, Flags: PUBLIC
OBJECT_FIELD_ENTRY = 0x0003  # Size: 1, Type: INT, Flags: PUBLIC
OBJECT_FIELD_SCALE_X = 0x0004  # Size: 1, Type: FLOAT, Flags: PUBLIC
OBJECT_END = 0x0006

# EItemFields
ITEM_FIELD_OWNER = OBJECT_END + 0x0000  # Size: 2, Type: LONG, Flags: PUBLIC
ITEM_FIELD_CONTAINED = OBJECT_END + 0x0002  # Size: 2, Type: LONG, Flags: PUBLIC
ITEM_FIELD_CREATOR = OBJECT_END + 0x0004  # Size: 2, Type: LONG, Flags: PUBLIC
ITEM_FIELD_STACK_COUNT = OBJECT_END + 0x0008  # Size: 1, Type: INT, Flags: OWNER, ITEM_OWNER
ITEM_FIELD_FLAGS = OBJECT_END + 0x000F  # Size: 1, Type: INT, Flags: PUBLIC
ITEM_FIELD_PROPERTY_SEED = OBJECT_END + 0x0034  # Size: 1, Type: INT, Flags: PUBLIC
ITEM_FIELD_RANDOM_PROPERTIES_ID = OBJECT_END + 0x0035  # Size: 1, Type: INT, Flags: PUBLIC
ITEM_FIELD_DURABILITY = OBJECT_END + 0x0036  # Size: 1, Type: INT, Flags: OWNER, ITEM_OWNER
ITEM_FIELD_MAXDURABILITY = OBJECT_END + 0x0037  # Size: 1, Type: INT, Flags: OWNER, ITEM_OWNER

# EUnitFields
UNIT_FIELD_TARGET = OBJECT_END + 0x000C  # Size: 2, Type: LONG, Flags: PUBLIC
UNIT_FIELD_BYTES_0 = OBJECT_END + 0x0011  # Size: 1, Type: BYTES, Flags: PUBLIC
UNIT_FIELD_HEALTH = OBJECT_END + 0x0012  # Size: 1, Type: INT, Flags: PUBLIC
UNIT_FIELD_POWER1 = OBJECT_END + 0x0013  # Size: 1, Type: INT, Flags: PUBLIC
UNIT_FIELD_MAXHEALTH = OBJECT_END + 0x001A  # Size: 1, Type: INT, Flags: PUBLIC
UNIT_FIELD_MAXPOWER1 = OBJECT_END + 0x001B  # Size: 1, Type: INT, Flags: PUBLIC
UNIT_FIELD_LEVEL = OBJECT_END + 0x0030  # Size: 1, Type: INT, Flags: PUBLIC
UNIT_FIELD_FACTIONTEMPLATE = OBJECT_END + 0x0031  # Size: 1, Type: INT, Flags: PUBLIC
UNIT_FIELD_FLAGS = OBJECT_END + 0x0035  # Size: 1, Type: INT, Flags: PUBLIC
UNIT_FIELD_DISPLAYID = OBJECT_END + 0x003D  # Size: 1, Type: INT, Flags: PUBLIC
UNIT_DYNAMIC_FLAGS = OBJECT_END + 0x0049  # Size: 1, Type: INT, Flags: DYNAMIC
UNIT_NPC_FLAGS = OBJECT_END + 0x004C  # Size: 1, Type: INT, Flags: DYNAMIC
UNIT_END = OBJECT_END + 0x008E
PLAYER_FLAGS = UNIT_END + 0x0002  # Size: 1, Type: INT, Flags: PUBLIC
PLAYER_QUEST_LOG_1_1 = UNIT_END + 0x000A  # Size: 1, Type: INT, Flags: PARTY_MEMBER
PLAYER_QUEST_LOG_2_1 = UNIT_END + 0x000F  # Size: 1, Type: INT, Flags: PARTY_MEMBER
PLAYER_VISIBLE_ITEM_1_ENTRYID = UNIT_END + 0x0087  # Size: 1, Type: INT, Flags: PUBLIC
PLAYER_FIELD_INV_SLOT_HEAD = UNIT_END + 0x00B0  # Size: 46, Type: LONG, Flags: PRIVATE
PLAYER_FIELD_PACK_SLOT_1 = UNIT_END + 0x00DE  # Size: 32, Type: LONG, Flags: PRIVATE
PLAYER_XP = UNIT_END + 0x01E6  # Size: 1, Type: INT, Flags: PRIVATE
PLAYER_NEXT_LEVEL_XP = UNIT_END + 0x01E7  # Size: 1, Type: INT, Flags: PRIVATE
PLAYER_FIELD_COINAGE = UNIT_END + 0x03FE  # Size: 1, Type: INT, Flags: PRIVATE

# EGameObjectFields
GAMEOBJECT_DISPLAYID = OBJECT_END + 0x0002  # Size: 1, Type: INT, Flags: PUBLIC
GAMEOBJECT_FLAGS = OBJECT_END + 0x0003  # Size: 1, Type: INT, Flags: PUBLIC
GAMEOBJECT_FACTION = OBJECT_END + 0x0009  # Size: 1, Type: INT, Flags: PUBLIC
GAMEOBJECT_LEVEL = OBJECT_END + 0x000A  # Size: 1, Type: INT, Flags: PUBLIC
# --- END GENERATED ---

# UNIT_FIELD_BYTES_0 packs race, class, gender, power_type (one byte each).
# UNIT_FIELD_POWER1 / UNIT_FIELD_MAXPOWER1 start 7-slot arrays (POWER1..POWER7).

# Quest log (UM-41): 25 slots (MAX_QUEST_LOG_SIZE) of 5 uint32 fields each
# (quest id, state, two packed-counter words, time), from PLAYER_QUEST_LOG_1_1
# up to PLAYER_VISIBLE_ITEM_1_ENTRYID. Both numbers are derived from generated
# header values (#290), not counted by hand. See docs/PROTOCOL-NOTES.md
# ("Quest log fields").
QUEST_LOG_FIELDS_PER_SLOT = PLAYER_QUEST_LOG_2_1 - PLAYER_QUEST_LOG_1_1
QUEST_LOG_SLOT_COUNT = (PLAYER_VISIBLE_ITEM_1_ENTRYID - PLAYER_QUEST_LOG_1_1) // QUEST_LOG_FIELDS_PER_SLOT

# Inventory/equipment item-GUID slots (UM-42): each slot is a guid (Size 2:
# low, high uint32). Equipment (0-18) and the 4 equipped-bag-container slots
# (19-22) share one contiguous 23-slot array at PLAYER_FIELD_INV_SLOT_HEAD;
# backpack contents (23-38, 16 slots) are a separate array right after it, at
# PLAYER_FIELD_PACK_SLOT_1. The counts are from
# src/server/game/Entities/Player/Player.h (EquipmentSlots/InventorySlots/
# InventoryPackSlots enums — the bag/slot numbers CMSG_AUTOSTORE_LOOT_ITEM,
# CMSG_USE_ITEM, CMSG_DESTROYITEM address).
EQUIPMENT_SLOT_COUNT = 19
BAG_SLOT_COUNT = 4          # equipped bag containers, slots 19-22
BACKPACK_SLOT_COUNT = 16    # slots 23-38
INVENTORY_SLOT_BAG_0 = 255  # pseudo-bag id meaning "equipped / main backpack" (Player.h)

# ITEM_FIELD_CONTAINED is the bag an item sits in, if any (UM-42).

# ── Type hints for the handful of fields decode_fields() reinterprets ────
FIELD_TYPE_FLOAT = "float"
FIELD_TYPE_GUID = "guid"      # occupies this slot and the next (low, high)
FIELD_TYPES = {
    OBJECT_FIELD_SCALE_X: FIELD_TYPE_FLOAT,
    UNIT_FIELD_TARGET: FIELD_TYPE_GUID,
}


def reinterpret_float(raw_u32: int) -> float:
    """A VALUES_UPDATE slot is always transmitted as a raw uint32; float
    fields need the bit pattern reinterpreted, not converted."""
    return struct.unpack('<f', struct.pack('<I', raw_u32 & 0xFFFFFFFF))[0]


def _guid_from_slots(raw: dict, index: int):
    if index not in raw:
        return None
    return raw[index] | (raw.get(index + 1, 0) << 32)


# TrinityCore branch `3.3.5`, src/server/shared/SharedDefines.h `enum Powers`
# — the type stored in UNIT_FIELD_BYTES_0's power_type byte and the meaning
# of UNIT_FIELD_POWER1..POWER7 / UNIT_FIELD_MAXPOWER1..MAXPOWER7 slot N (this
# is NOT positional: a class only sends the slots for the powers it has, so
# slot 0 is "mana" only when mana happens to be the first power present —
# UM-70). POWER_NAMES[i] is the name for slot offset i (0-6).
POWER_MANA = 0
POWER_RAGE = 1
POWER_FOCUS = 2
POWER_ENERGY = 3
POWER_HAPPINESS = 4
POWER_RUNE = 5
POWER_RUNIC_POWER = 6
POWER_NAMES = ("mana", "rage", "focus", "energy", "happiness", "rune", "runic_power")


def _decode_power_slots(raw: dict, base_index: int) -> dict:
    """{power_name: value} for whichever of the 7 POWER/MAXPOWER slots
    starting at `base_index` are present in `raw` — keyed by Powers enum
    name so index/key always means the same power type regardless of which
    slots the server actually sent (UM-70)."""
    out = {}
    for i in range(7):
        index = base_index + i
        if index in raw:
            out[POWER_NAMES[i]] = raw[index]
    return out


def decode_fields(object_type: int, raw: dict) -> dict:
    """Named, typed values from `raw` (agent.update_object's VALUES_UPDATE
    field dict: {field_index: uint32}). Only maps the fields listed in the
    UM-33 card; anything else stays reachable via `raw_fields` rather than
    being silently dropped — cheaper to keep than to re-add slots every time
    a new field turns out to matter."""
    out = {"raw_fields": dict(raw)}

    if OBJECT_FIELD_ENTRY in raw:
        out["entry"] = raw[OBJECT_FIELD_ENTRY]
    if OBJECT_FIELD_SCALE_X in raw:
        out["scale"] = reinterpret_float(raw[OBJECT_FIELD_SCALE_X])

    if object_type in (uo.TYPEID_UNIT, uo.TYPEID_PLAYER):
        if UNIT_FIELD_HEALTH in raw:
            out["health"] = raw[UNIT_FIELD_HEALTH]
        if UNIT_FIELD_MAXHEALTH in raw:
            out["max_health"] = raw[UNIT_FIELD_MAXHEALTH]
        if UNIT_FIELD_LEVEL in raw:
            out["level"] = raw[UNIT_FIELD_LEVEL]
        if UNIT_FIELD_FACTIONTEMPLATE in raw:
            out["faction"] = raw[UNIT_FIELD_FACTIONTEMPLATE]
        if UNIT_FIELD_FLAGS in raw:
            out["unit_flags"] = raw[UNIT_FIELD_FLAGS]
        if UNIT_DYNAMIC_FLAGS in raw:
            out["dynamic_flags"] = raw[UNIT_DYNAMIC_FLAGS]
        if UNIT_NPC_FLAGS in raw:
            out["npc_flags"] = raw[UNIT_NPC_FLAGS]
        if UNIT_FIELD_DISPLAYID in raw:
            out["display_id"] = raw[UNIT_FIELD_DISPLAYID]

        target_guid = _guid_from_slots(raw, UNIT_FIELD_TARGET)
        if target_guid is not None:
            out["target_guid"] = target_guid

        power = _decode_power_slots(raw, UNIT_FIELD_POWER1)
        if power:
            out["power"] = power
        max_power = _decode_power_slots(raw, UNIT_FIELD_MAXPOWER1)
        if max_power:
            out["max_power"] = max_power

        if UNIT_FIELD_BYTES_0 in raw:
            bytes0 = raw[UNIT_FIELD_BYTES_0]
            out["race"] = bytes0 & 0xFF
            out["class_"] = (bytes0 >> 8) & 0xFF
            out["gender"] = (bytes0 >> 16) & 0xFF
            out["power_type"] = (bytes0 >> 24) & 0xFF

    if object_type == uo.TYPEID_PLAYER:
        if PLAYER_FLAGS in raw:
            out["player_flags"] = raw[PLAYER_FLAGS]
        if PLAYER_XP in raw:
            out["xp"] = raw[PLAYER_XP]
        if PLAYER_NEXT_LEVEL_XP in raw:
            out["next_level_xp"] = raw[PLAYER_NEXT_LEVEL_XP]
        if PLAYER_FIELD_COINAGE in raw:
            out["coinage"] = raw[PLAYER_FIELD_COINAGE]

    if object_type == uo.TYPEID_GAMEOBJECT:
        if GAMEOBJECT_DISPLAYID in raw:
            out["display_id"] = raw[GAMEOBJECT_DISPLAYID]
        if GAMEOBJECT_FLAGS in raw:
            out["gameobject_flags"] = raw[GAMEOBJECT_FLAGS]
        if GAMEOBJECT_FACTION in raw:
            out["faction"] = raw[GAMEOBJECT_FACTION]
        if GAMEOBJECT_LEVEL in raw:
            out["level"] = raw[GAMEOBJECT_LEVEL]

    if object_type in (uo.TYPEID_ITEM, uo.TYPEID_CONTAINER):
        out.update(decode_item_fields(raw))

    return out


def decode_item_fields(raw: dict) -> dict:
    """Named, typed values for an ITEM/CONTAINER object's VALUES_UPDATE
    fields (UM-42) — used both from decode_fields() above (for objects
    perceived generically through update-object) and directly by
    agent.perception.WorldState when building session.inventory from the
    self player's own item objects."""
    out = {}
    if OBJECT_FIELD_ENTRY in raw:
        out["entry"] = raw[OBJECT_FIELD_ENTRY]
    owner = _guid_from_slots(raw, ITEM_FIELD_OWNER)
    if owner is not None:
        out["owner_guid"] = owner
    contained = _guid_from_slots(raw, ITEM_FIELD_CONTAINED)
    if contained is not None:
        out["contained_guid"] = contained
    if ITEM_FIELD_STACK_COUNT in raw:
        out["count"] = raw[ITEM_FIELD_STACK_COUNT]
    if ITEM_FIELD_FLAGS in raw:
        out["item_flags"] = raw[ITEM_FIELD_FLAGS]
    if ITEM_FIELD_RANDOM_PROPERTIES_ID in raw:
        out["random_property_id"] = raw[ITEM_FIELD_RANDOM_PROPERTIES_ID]
    if ITEM_FIELD_PROPERTY_SEED in raw:
        out["property_seed"] = raw[ITEM_FIELD_PROPERTY_SEED]
    if ITEM_FIELD_DURABILITY in raw:
        out["durability"] = raw[ITEM_FIELD_DURABILITY]
    if ITEM_FIELD_MAXDURABILITY in raw:
        out["max_durability"] = raw[ITEM_FIELD_MAXDURABILITY]
    return out


def decode_quest_log(raw: dict) -> list:
    """The self player's quest log (UM-41): up to QUEST_LOG_SLOT_COUNT
    slots, each PLAYER_QUEST_LOG_x_1..x_5 (quest id, state, two
    packed-counter words, time — see PLAYER_QUEST_LOG_1_1 above). A slot
    with quest id 0 (or absent — zero-value fields aren't sent over the
    wire, same caveat as PLAYER_FIELD_COINAGE elsewhere in this module) is
    empty and skipped. Each packed-counter word holds two uint16 objective
    counters (low half, high half) — TrinityCore's `QuestSlotOffsets`
    (`Player.h`) packs up to 4 kill/item counters into the two x_3/x_4
    words this way. Returns a list sorted by slot, not keyed by quest id,
    since two log slots could (in principle, e.g. a bugged/duplicated
    quest) carry the same quest id."""
    out = []
    for slot in range(QUEST_LOG_SLOT_COUNT):
        base = PLAYER_QUEST_LOG_1_1 + slot * QUEST_LOG_FIELDS_PER_SLOT
        quest_id = raw.get(base)
        if not quest_id:
            continue
        state = raw.get(base + 1, 0)
        counters_a = raw.get(base + 2, 0)
        counters_b = raw.get(base + 3, 0)
        qtime = raw.get(base + 4, 0)
        counters = [
            counters_a & 0xFFFF, (counters_a >> 16) & 0xFFFF,
            counters_b & 0xFFFF, (counters_b >> 16) & 0xFFFF,
        ]
        out.append({
            "slot": slot, "quest_id": quest_id, "state": state,
            "counters": counters, "time": qtime,
        })
    return out


def decode_equipment_and_inventory_guids(raw: dict) -> dict:
    """The self player's equipment (slots 0-18), equipped-bag-container
    (slots 19-22) and backpack (slots 23-38) item GUIDs, keyed by slot
    number 0-38 (matching the bag/slot numbering CMSG_AUTOSTORE_LOOT_ITEM /
    CMSG_USE_ITEM / CMSG_DESTROYITEM use with bag=INVENTORY_SLOT_BAG_0).
    Only nonzero (occupied) slots are included."""
    out = {}
    total = EQUIPMENT_SLOT_COUNT + BAG_SLOT_COUNT
    for i in range(total):
        guid = _guid_from_slots(raw, PLAYER_FIELD_INV_SLOT_HEAD + i * 2)
        if guid:
            out[i] = guid
    for i in range(BACKPACK_SLOT_COUNT):
        guid = _guid_from_slots(raw, PLAYER_FIELD_PACK_SLOT_1 + i * 2)
        if guid:
            out[EQUIPMENT_SLOT_COUNT + BAG_SLOT_COUNT + i] = guid
    return out
